project_name: OpenSesame

# Packaging only the binaries, only the binary will be added to the archive.
archives:
- files:
  - none*

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
    goarch:
      - amd64

nfpms:
- maintainer: Tong Sun <suntong@cpan.org>
  description: Open Sesame project.
  homepage: https://github.com/suntong/OpenSesame
  license: MIT
  formats:
  - deb
  - rpm
  - apk
 
