# -*- yaml -*-

language: go
# -*- yaml -*-

language: go

go:
- 1.15.x

env:
  global:
    # Package setup (Ref: http://pkg-go.alioth.debian.org/packaging.html)
    - VERSION="${TRAVIS_TAG:=0.0~git$(date +%Y%m%d)-1}"
    - PKG_NAME="OpenSesame"
    - PKG_URL="https://github.com/suntong/OpenSesame"
    - PKG_CAT=utils
    - PKG_ARCH=amd64
    - PKG_DESC="Open Sesame -- One-time based file sharing"
    - PKG_VEND="suntong"
    - PKG_MAINT='Tong Sun <suntong@cpan.org>'
    - PKG_LICNS="MIT"
    # Build time setup
    - TZ=America/Toronto
    - DATE_BUILD=`date -I`

script:

  - date
  - echo $DATE_BUILD $VERSION
  - echo

  - go get -t -v ./...
  - go build -v -ldflags="-X main.date=$DATE_BUILD"
  - OpenSesame -help
  - go test -v ./...

